#!/bin/sh
# ============================================================
# Nexus — Vercel Build Script
# build.sh
#
# Vercel runs this before serving the static files.
# It reads SUPABASE_URL and SUPABASE_ANON from Vercel
# Environment Variables and writes them into config.js.
#
# This way your keys never live in the repo — they only
# exist in Vercel's secure environment variable store.
# ============================================================

echo "🔧 Nexus build: generating config.js from environment variables..."

cat > config.js << EOF
/* Auto-generated by build.sh at deploy time. Do not edit. */
window.NEXUS_CONFIG = {
  SUPABASE_URL:  '${SUPABASE_URL}',
  SUPABASE_ANON: '${SUPABASE_ANON}',
};
EOF

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON" ]; then
  echo "⚠️  Warning: SUPABASE_URL or SUPABASE_ANON is not set."
  echo "   The app will run in demo mode."
  echo "   Add them in Vercel → Settings → Environment Variables."
else
  echo "✅ Supabase credentials injected into config.js"
fi

echo "🚀 Build complete."
